### ISSUE TITLE
add --with-lua-ver

### ISSUE THREAD

**Issue by jhgit** [freebsd/lutok#1]
This patch adds --with-lua-ver to configure to specify a particular version of lua (if you have more than one installed).  It also adds lua 5.3 to the default search list.

[pr-lutok-luaver.txt](https://github.com/jmmv/lutok/files/753327/pr-lutok-luaver.txt)

**Comment by ncopa** [comment]
This was sort of fixed with #12. You can specify lua version with `LUA_VERSION`. Do we want a configure option for it in addition?

**Comment by fel1x-developer** [comment]
> Do we want a configure option for it in addition?

I'm against this. Usually it is a person who manages toolchain versions, not source code.

**Comment by ngie-eign** [comment]
I'm in agreement with @ncopa and @fel1x-developer -- there are far too many OS distro specific ways of distributing packages. The goal of this package should be to be as generic as possible. Distro maintainers should be adjusting the build process to fit their needs.
