### ISSUE TITLE
lutok fails to compile on NetBSD 7.x-CURRENT

### ISSUE THREAD

**Issue by ngie-eign** [freebsd/lutok#2]
From http://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=52080 :

<pre>
>Environment:
NetBSD netbsd.localdomain 7.99.58 NetBSD 7.99.58 (GENERIC) #2: Thu Jan 12 09:08:18 PST 2017  root@:/home/ngie/cvs/NetBSD/src/sys/arch/amd64/compile/obj/GENERIC amd64
>Description:
lutok fails to compile because it seems like it's accessing headers it's not supposed to (private ones):

--- c_gate.o ---^M
In file included from /home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/g++/bits/ostream_insert.h:36:0,^M
                 from /home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/g++/string:44,^M
                 from /home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/lutok/state.hpp:35,^M
                 from /home/ngie/cvs/NetBSD/src/external/bsd/lutok/dist/state.ipp:32,^M
                 from /home/ngie/cvs/NetBSD/src/external/bsd/lutok/dist/c_gate.cpp:30:^M
/home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/g++/bits/cxxabi_forced.h:48:9: error: all member functions in class '__cxxabiv1::__forced_unwind' are private [-Werror=ctor-dtor-privacy]^M
   class __forced_unwind^M
         ^^M
In file included from /home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/g++/tr1/memory:50:0,^M
                 from /home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/lutok/state.hpp:40,^M
                 from /home/ngie/cvs/NetBSD/src/external/bsd/lutok/dist/state.ipp:32,^M
                 from /home/ngie/cvs/NetBSD/src/external/bsd/lutok/dist/c_gate.cpp:30:^M
/home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/g++/tr1/shared_ptr.h: In constructor 'std::tr1::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Tp1*)':^M
/home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/g++/tr1/shared_ptr.h:556:16: error: typedef '_IsComplete' locally defined but not used [-Werror=unused-local-typedefs]^M
    typedef int _IsComplete[sizeof(_Tp1)];^M
                ^^M
/home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/g++/tr1/shared_ptr.h: In constructor 'std::tr1::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::auto_ptr<_Tp1>&)':^M
/home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/g++/tr1/shared_ptr.h:595:16: error: typedef '_IsComplete' locally defined but not used [-Werror=unused-local-typedefs]^M
    typedef int _IsComplete[sizeof(_Tp1)];^M
                ^^M
--- c_gate.pico ---^M
In file included from /home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/g++/bits/ostream_insert.h:36:0,^M
                 from /home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/g++/string:44,^M
                 from /home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/lutok/state.hpp:35,^M
                 from /home/ngie/cvs/NetBSD/src/external/bsd/lutok/dist/state.ipp:32,^M
                 from /home/ngie/cvs/NetBSD/src/external/bsd/lutok/dist/c_gate.cpp:30:^M
/home/ngie/cvs/NetBSD/src/obj/destdir.amd64/usr/include/g++/bits/cxxabi_forced.h:48:9: error: all member functions in class '__cxxabiv1::__forced_unwind' are private [-Werror=ctor-dtor-privacy]^M
   class __forced_unwind^M
         ^^M
--- c_gate.o ---^M
cc1plus: all warnings being treated as errors^M

I will file an upstream bug (if one doesn't already exist), as this will likely hit us on FreeBSD if someone tries compiling the lutok port with a newer copy of g++ (which we do for arm64, powerpc*, etc as they still don't work with clang).
>How-To-Repeat:
Run the following commands as root:

echo MKKYUA=yes >> /etc/mk.conf
cd /path/to/src
./build.sh tools
./build.sh build
>Fix:
Either disable warnings, or fix the offending code to not use private C++ interfaces.
</pre>

**Comment by jmmv** [comment]
I haven't tried to reproduce this yet but... the first error in the log above points to an `#include <string>`, which is very strange -- and to my knowledge Lutok doesn't use any "private C++ interfaces".

What version of `c++` is that?

**Comment by yaneurabeya** [comment]
`obj/tooldir.NetBSD-7.99.58-amd64/bin/x86_64--netbsd-c++ --version` says `5.4.0`.

**Comment by fel1x-developer** [comment]
This issue is now resolved in NetBSD. [NetBSD PR](https://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=52080)

> State-Changed-From-To: open->closed
State-Changed-By: bsiegert@NetBSD.org
State-Changed-When: Sat, 20 Feb 2021 14:28:25 +0000
State-Changed-Why:
This looks very much like temporary brokenness of the C++ toolchain
in NetBSD 7.99.x in 2017.
>
> Newer NetBSD releases use newer gcc versions.
> 
> jmmv@ determined that this does not seem to be related to anything in the actual code.
> Closing.
